WEB-Auction/Controllers/LotController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Business_Logic_Layer.Models;
using WEB_Auction.Models;
using Business_Logic_Layer.Abstract;

namespace WEB_Auction.Controllers
{
    public class LotController : Controller
    {
        private readonly ILotService _lotService;
        private readonly IAuctionService _auctionService;
        private readonly IUserService _userService;
        public LotController(ILotService lotService, IAuctionService auctionService, IUserService userService)
        {
            _lotService = lotService;
            _auctionService = auctionService;
            _userService = userService;
        }
        // public  Task<ActionResult<IEnumerable<LotDto>>> GetAll()
        //    => Ok( _lotService.GetAllAsync());
        [HttpGet("{id}")]
        public async Task<ActionResult<LotDto>> GetById(int id)
            => Ok(await _lotService.GetByIdAsync(id));
        [HttpGet]
        public ActionResult Index(int id) 
        {
            var list = _lotService.GetByAuctionId(id);
            LotModel model = new LotModel(list);
            return View(model);
        }
        [HttpGet]
        public ActionResult Add(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(LotModel model)
        {
            var auctionId = Convert.ToInt32(RouteData.Values["id"]);
            var currentUser =  _userService.GetByEmail(User.Identity.Name);
            var currentUserId = currentUser.Result.Id;
            var auctionUser = _auctionService.GetByIdAsync(auctionId);
            var auctionUserId = auctionUser.Result.UserId;
            if (currentUserId == auctionUserId) 
            {
                _lotService.AddAsync(new LotDto { Name = model.Name, Price = model.Bid, Description = model.Description
                    , BidUserId=currentUserId, Expiring = model.Expiring, AuctionId=auctionId });
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult MakeBid(int id) 
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> MakeBid(BidModel model)
        {
            string bidUserName = User.Identity.Name;
            var user = await _userService.GetByEmail(bidUserName);
            var id = user.Id;
            var lotId = Convert.ToInt32(RouteData.Values["id"]);
            _lotService.UpdateBidAsync(lotId, id, model.BidValue);
            return View(model);
        }
        [HttpDelete("{id}")]
        public async Task<ActionResult> Delete(int id) 
        {
            await _lotService.DeleteAsync(id);
            return Ok();
        }
        //[HttpGet]
        //public IActionResult Index()
        //{
        //    var list = _lotService.GetAllAsync().ToList();
        //    LotModel model = new LotModel(list);
        //    return View(model);
        //}
    }
}

WEB-Auction/Views/Lot/Add.cshtml
@model WEB_Auction.Models.LotModel

<h2>Создать лот</h2>
<form asp-action="Add" asp-controller="Lot" asp-anti-forgery="true">
    <div>
        <div>
            <label asp-for="Name">Введите название</label><br />
            <input type="text" asp-for="Name" />
        </div>
        <div>
            <label asp-for="Description">Введите описание</label><br />
            <input asp-for="Description" />
        </div>
        <div>
            <label asp-for="Bid">Введите начальную сумму</label><br />
            <input asp-for="Bid" />
        </div>
        <div>
            <label asp-for="Expiring">Введите дату окончания аукциона</label><br />
            <input asp-for="Expiring" />
        </div>
        <div>
            <input type="submit" value="Создать" />
        </div>
    </div>
</form>

WEB-Auction/Views/Lot/Index.cshtml
@using Business_Logic_Layer.Models;
@model WEB_Auction.Models.LotModel

@foreach (var l in Model.Lots)
{
<tr>
    <td><p>ID:@l.Id</p></td>
    <td><p>Название лота:@l.Name</p></td>
    <td><p>Описание лота:@l.Description</p></td>
    <td><p>Текущая цена лота:@l.Price</p></td>
    <td><p>Истекает в:@l.Expiring</p></td>
    @Html.ActionLink("Выбрать лот", "MakeBid", "Lot", new { id = l.Id })
</tr>
}

WEB-Auction/Views/Lot/MakeBid.cshtml
@using Business_Logic_Layer.Models;
@model WEB_Auction.Models.BidModel

<h2>Сделать ставку</h2>

<form asp-action="MakeBid" asp-controller="Lot" asp-anti-forgery="true">
    <div>
        <div>
            <label asp-for="BidValue">Введите значение</label><br />
            <input type="text" asp-for="BidValue" />
        </div>
        <div>
            <input type="submit" value="Подтвердить ставку" />
        </div>
    </div>
</form>